server:
  log_level: debug

# Configures a metrics scraping service, used to scrape metrics and send
# to Mimir.
metrics:
  global:
    scrape_interval: 15s # By default, scrape targets every 15 seconds.
    remote_write:
      - url: http://mimir:9009/api/v1/push

  configs:
    - name: default
      scrape_configs:
      
      - job_name: 'loki'
        scrape_interval: 15s
        static_configs:
          - targets: ['loki:3100']
            labels:
              group: 'loki'   

      - job_name: minio-job
        scrape_interval: 15s
        metrics_path: /minio/v2/metrics/cluster
        static_configs:
          - targets: ['minio:9000']   
            labels:
              group: 'minio'                 